### ISSUE TITLE
Can only spawn tuxedo cats

### ISSUE THREAD

**Issue by wingedseahorse** [nyuppo/MobVariants#1]
All other mobs added appear to be working fine except cats. Which, as above, will only spawn vanilla tux cats with an egg. Uninstalled and cat spawns immediately returned to normal. 

sorry- i see on git is has already been fixed but not pushed to modrith yet :+1:

**Comment by nyuppo** [comment]
Crap, thanks for letting me know I never uploaded it to modrinth haha, just uploaded it!
