### ISSUE TITLE
monster spawner textures appear to be broken

### ISSUE THREAD

**Issue by notandvm** [nyuppo/MobVariants#11]
> base fabric 1.20.1 instance
> fabric api, more mob variants (1.2.2)

while mob textures are unaffected it appears the game is unable to locate default textures for chickens, cows, pigs, sheep, wolves, and zombies, leading to missing textures within mob spawners, and the log spits out errors regarding them:

[relevant log details.txt](https://github.com/nyuppo/MobVariants/files/12364844/relevant.log.details.txt)
[latest.log](https://github.com/nyuppo/MobVariants/files/12364852/latest.log)

cat spawners however don't seem to have this issue

![2023-08-16_22 22 53](https://github.com/nyuppo/MobVariants/assets/137728158/f549174d-aa95-42e6-a790-87f132b1616a)

**Comment by nyuppo** [comment]
This'll be fixed in the upcoming 1.3.0 update.
