### ISSUE TITLE
[1.20.1] Mixin injecting SynchedEntityData into entities not owned by MobVariants is dangerous

### ISSUE THREAD

**Issue by TelepathicGrunt** [nyuppo/MobVariants#16]
Entity Data Accessors should only be ever set by the creator of the entity. Never added to by other mods.

The reason for this is because Entity Data Accessors are order dependent so if multiple mods tries to add these entity data accessors to mobs and on client, they run in a different order than the server did (because mod load order is not guaranteed), the client will get forcibly disconnected from server when the entity spawns.

Instead, this mixin part needs to be removed and migrated properly to a Forge Capability because capabilities were designed specifically for this use case of attaching data to arbitrary entities. It is safer for mods as the vanilla system is designed specifically only for vanilla and unsafe for mods. Then you would use your own packet to send the data to client when needed.

https://github.com/nyuppo/MobVariants/blob/5c70ed44fc99e77e9e201d881b2ba5b86057efd4/src/main/java/com/github/nyuppo/mixin/ChickenVariantsMixin.java#L27

https://github.com/nyuppo/MobVariants/blob/5c70ed44fc99e77e9e201d881b2ba5b86057efd4/src/main/java/com/github/nyuppo/mixin/CowVariantsMixin.java#L26

https://github.com/nyuppo/MobVariants/blob/5c70ed44fc99e77e9e201d881b2ba5b86057efd4/src/main/java/com/github/nyuppo/mixin/PigVariantsMixin.java#L27

and other files as well.

This is especially a problem in large modpacks where many mods are doing this. Example is TNPLimitless 7 where there's many mods injecting SynchedEntityData onto entities and are getting out of order due to mod load order. Which is causes a lot of reports of people getting disconnected from server due to: 
![image](https://github.com/nyuppo/MobVariants/assets/40846040/bef1a1b9-dca3-48de-8179-1cf71bc6d573)

**Comment by nyuppo** [comment]
I know you mention replacing that mixin part with Forge Capabilities, does that only apply to the Forge version of this mod or is there an equivalent for the Fabric version? I'm assuming that the issue would occur on both modloaders.

**Comment by TelepathicGrunt** [comment]
Fabric can use Cardinal components as the equivalent of forge caps. 

Another option is to change this field to be a normal field (not a data accessor at all) and send your own packet to client to set the client values. Supplementaries dev did a similar fix https://github.com/MehVahdJukaar/Supplementaries/issues/851#issuecomment-1832959877

**Comment by nyuppo** [comment]
Got it, thanks for the tip. I'll start switching everything over, haven't received any reports of this actually occurring yet but I'm already refactoring everything with this update so might as well fix it now lol

**Comment by nyuppo** [comment]
Reached out to you on discord to review some changes before I mark this as resolved.

**Comment by nyuppo** [comment]
Fixed in the upcoming 1.3.0 update, data syncing is now done manually between the server and client.
