### ISSUE TITLE
1.20.2 ETA?

### ISSUE THREAD

**Issue by Santiag09** [nyuppo/MobVariants#17]
I know programing can be crazy hard work and I respect the dev's soo much for said reasoning, however I wanted to check if there's an ETA yet?

**Comment by nyuppo** [comment]
Sorry for the wait, it is on the horizon now! One last feature is being tested and then the mod just needs to be ported to Forge and it is good to go! Feel free to join my discord to keep up to date with development: https://discord.gg/CeTHcXUJJv
