### ISSUE TITLE
Puppies need to be tamed?

### ISSUE THREAD

**Issue by setzke** [nyuppo/MobVariants#18]
Hey, is this a bug or a feature? When breeding dogs / wolves, the puppy always needs to be tamed. I tested by removing your mod, breeding some pups, and the puppy is tame. Re-enable mod, breed, and poof another wild puppy. Please advise!

1.20.2, Fabric, Mod version 1.2.2.

**Comment by nyuppo** [comment]
Yeah the mod wasn't carrying over data like this or sheep colours when breeding, it'll be fixed in the upcoming 1.3.0 update.
