### ISSUE TITLE
Question: Server only option? Cats?

### ISSUE THREAD

**Issue by setzke** [nyuppo/MobVariants#19]
Hello!

If the custom cats were removed, would this allow the mod to exist only on server side, and clients would just see normal of the other mods?

If so, is this version hiding anywhere? It's unfortunately becoming a hassle to find players unable to join because of they're missing 4 or something... I assume the cats.

Thanks!

**Comment by nyuppo** [comment]
This'll be added in the upcoming 1.3.0 update, custom variants will show up as vanilla black cats to anyone who doesn't have the mod.
