### ISSUE TITLE
Unchecked read from nbt creates namespace only identifier

### ISSUE THREAD

**Issue by Linguardium** [nyuppo/MobVariants#20]
https://github.com/nyuppo/MobVariants/blob/5c70ed44fc99e77e9e201d881b2ba5b86057efd4/src/main/java/com/github/nyuppo/mixin/ZombieVariantsMixin.java#L39

This creates issues with mods like trofers that generate entities that dont tick. 

best practice is to check for the presence of the nbt and if it isnt present, use a default.  If you previously used an empty string, you may want to instead set it to default if empty after reading since a readString when the key is missing will return an empty string.

**Comment by nyuppo** [comment]
This should be fixed in the upcoming 1.3.0 update, thanks!
