### ISSUE TITLE
Bug with Fresh Animations CEM Fork (1.19.2)

### ISSUE THREAD

**Issue by ginsm** [nyuppo/MobVariants#3]
Here's the link to [Fresh Animations CEM Fork](https://github.com/YoungSoulluoS/Fresh-Animations-CEM-fork). The [pink footed](https://github.com/nyuppo/MobVariants/blob/master/src/main/resources/assets/moremobvariants/textures/entity/pig/pink_footed.png) and [sooty](https://github.com/nyuppo/MobVariants/blob/master/src/main/resources/assets/moremobvariants/textures/entity/pig/sooty.png) pig variants have a strange square above their heads ([see picture](https://i.imgur.com/ekJU7MB.png)). Is the top left portion of the texture needed? 🤔

**Comment by nyuppo** [comment]
Thanks for bringing this to my attention! Those parts of the texture were unnecessary, and have been removed.

**Comment by ginsm** [comment]
Awesome, is there any chance to have the change backported to 1.19.2? ❤️

**Comment by TheEscaper** [comment]
I encoutered the same issue. I simply edited both sprites in photoshop and replaced those inside the jar file
