### ISSUE TITLE
[Bug] 1.20.1 Crash

### ISSUE THREAD

**Issue by IntM4rco** [nyuppo/MobVariants#30]
The have lots of mods so I don't know if is incompatible bug or something else

https://mclo.gs/feADJE4

**Comment by IntM4rco** [comment]
Here the .mrpack file if u wanna test it

https://drive.google.com/file/d/1P9a0zEObQOtycJCHdA9T2vE1us2t2kc9/view?usp=sharing

**Comment by nyuppo** [comment]
Thanks for the report, someone else had a near-identical issue. Looking into it.

**Comment by fzzyhmstrs** [comment]
We are also repeatedly experiencing this crash

[guard_crash.txt](https://github.com/nyuppo/MobVariants/files/15063935/guard_crash.txt)

**Comment by fzzyhmstrs** [comment]
created a PR to fix it, pending testing.
