### ISSUE TITLE
Log Spam & Legacy Random Source Access

### ISSUE THREAD

**Issue by Fyoncle** [nyuppo/MobVariants#36]
https://mclo.gs/CyLGGIR

Heres the log spam.

**Comment by Routhinator** [comment]
Seeing this and in my case this is more than causing spam, it's causing crashes during chunk pregeneration.

**Comment by Fyoncle** [comment]
> Seeing this and in my case this is more than causing spam, it's causing crashes during chunk pregeneration.

Yep! And it lately MMV got incompatible with Meadow so i removed it, but still thats a glitch so.

**Comment by Fyoncle** [comment]
The pull request merged so ill close this issue.
