### ISSUE TITLE
1.21 version crashes on start up

### ISSUE THREAD

**Issue by TheRedBrain** [nyuppo/MobVariants#44]
This is caused by an invalid mixin.

The mixin at
https://github.com/nyuppo/MobVariants/blob/master/src/main/java/com/github/nyuppo/mixin/MobEntityVariantsMixin.java#L38
has a invalid target definition.

MobEntity.initialize no longer takes a '@ Nullable NbtCompound entityNbt' as the last argument.

**Comment by nyuppo** [comment]
bugs that don't happen in dev but happen in prod should be illegal
