### ISSUE TITLE
[1.20.1] version 1.20-1.2.1 crashes dedicated server on launch

### ISSUE THREAD

**Issue by karelmikie3** [nyuppo/MobVariants#7]
Installing the mod causes the server to crash on launch due to it trying to load client-side-only classes.
mc version: 1.20.1
forge version: 47.1.0
mod version: 1.20-1.2.1

logs:
[crash-2023-07-07_14.43.28-fml.txt](https://github.com/nyuppo/MobVariants/files/11982098/crash-2023-07-07_14.43.28-fml.txt)
[latest.log](https://github.com/nyuppo/MobVariants/files/11982104/latest.log)
[debug.log](https://github.com/nyuppo/MobVariants/files/11982106/debug.log)

**Comment by nyuppo** [comment]
Just pushed a 1.2.2 update that should fix this problem!
